core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (
        HomeView,
        ItemDetailView,
        CheckoutView,
        add_to_cart,
        remove_from_cart,
        remove_single_item_from_cart,
        OrderSummaryView,
        StripeIntentView,
        StripeSuccessView,
        Stripe_webhook,
        Order_pick_up_success_View,
        HomeCategorySearchView,
        HomeSearchView
        #PaymentView
    ) 

app_name = 'core'

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('categories/<int:pk>', HomeCategorySearchView.as_view(), name='category_search'),
    path('search/', HomeSearchView.as_view(), name='home_search'),
    path('checkout/',CheckoutView.as_view(),name = 'checkout'),
    path('product/<slug>',ItemDetailView.as_view(),name = 'product'),
    path('add-to-cart/<slug>', add_to_cart, name = 'add-to-cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name = 'remove-from-cart'),
    path('remove-single-item-from-cart/<slug>', remove_single_item_from_cart, name = 'remove-single-item-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name= 'order-summary'),
    #path('payment/<payment_option>/',PaymentView.as_view(), name = 'payment' ),
    path('create-payment-intent/',StripeIntentView.as_view(), name = 'create-payment-intent' ),
    path('create-payment-success/',StripeSuccessView.as_view(), name = 'create-payment-success'),
    path('webhooks/stripe/',Stripe_webhook,name = 'Stripe-webhook'  ),
    path('Order_pick_up_success_View',Order_pick_up_success_View.as_view(), name = 'Order-pick-up-success-View')
    
] 

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('core.urls',namespace='core'))
]

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from autoslug import AutoSlugField
import os.path
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.dispatch import receiver
from django.db.models.signals import pre_save,post_delete
import dropbox



#from django_q.models import Schedule


#Schedule.objects.create(
#    func='core.tasks.test_task',
#    minutes=1,  # run every 5 minutes
#    repeats=-1  # keep repeating, repeat forever
#)

# Create your models here.

CATEGORY_CHOICES = (
    ('HM','Hornos'),
    ('O','otros')
)

LABEL_CHOICES = (
    ('P','primary'),
    ('S','secondary'),
    ('T','third')
)

PAYMENT_CHOICES = (
    ('C','cash'),
    ('S','stripe')    
)

PAYMENT_STATUS = (
    ('F','fulfilled'),
    ('P','pending')    
)

DELIVERY_CHOICES = (
    ('P','pickup'),
    ('S','shipping')    
)

#--------------------------------------------------------

#----------------------------------------------------------

class Category(models.Model):
    title = models.CharField(max_length=100,default='Otros')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'



class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True,null=True)
    shipping_cost = models.FloatField(default=0)
    #category = models.CharField(choices=CATEGORY_CHOICES,max_length=2,default='O')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default= None)
    label = models.CharField(choices=LABEL_CHOICES,max_length=1,default='P')
    #slug = models.SlugField(default = 'test-product')
    slug = AutoSlugField(populate_from='title',unique=True)
    description = models.TextField(default = 'test description')
    stock = models.IntegerField(default=1)
    id_item = models.CharField(max_length=20,default='0')
    image = models.ImageField(upload_to='work_image/', verbose_name=('imagen'),null=True,blank=True)
    thumbnail = models.ImageField(editable=False, upload_to='work_image',null=True,blank=True)
    image2 = models.ImageField(upload_to='work_image/', verbose_name=('imagen2'),null=True,blank=True)
    image3 = models.ImageField(upload_to='work_image/', verbose_name=('imagen3'),null=True,blank=True)
    
     # Class string added to store original name of photo
    original_image_name = None 
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})
    
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={"slug": self.slug})
    
    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={"slug": self.slug})
    
      # When the form is initialized save the original photo name
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_photo_name = self.title
    
    
        
    def save(self, *args, **kwargs):
        # This checks if the photo was updated or not before saving a thumbnail
        
                   
        if self.original_image_name != self.title:
            pass 
            if not self.make_thumbnail():
                # set to a default thumbnail
                #raise Exception('Could not create thumbnail - is the file type valid?')
                print("Could not create thumbnail")   
        
        super(Item, self).save(*args, **kwargs)
    
    def make_thumbnail(self):
        
       # print(default_storage.exists(self.thumbnail.name))
       # if default_storage.exists(self.thumbnail.name) == True:
       #     return True
        try: 
            image = Image.open(self.image)
            image.thumbnail(settings.THUMB_SIZE, Image.ANTIALIAS)
            
            image_name = os.path.basename(self.image.name)
            
            thumb_name, thumb_extension = os.path.splitext(image_name)
            
            thumb_extension = thumb_extension.lower()

            thumb_filename = thumb_name + '_thumb' + thumb_extension

            if thumb_extension in ['.jpg', '.jpeg']:
                FTYPE = 'JPEG'
            elif thumb_extension == '.gif':
                FTYPE = 'GIF'
            elif thumb_extension == '.png':
                FTYPE = 'PNG'
            elif thumb_extension == '.webp':
                FTYPE = 'WEBP'
            else:
                return False    # Unrecognized file type

            # Save thumbnail to in-memory file as StringIO
            temp_thumb = BytesIO()
            image.save(temp_thumb, FTYPE)
            temp_thumb.seek(0)

            # set save=False, otherwise it will run in an infinite loop
            self.thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
            temp_thumb.close()

            return True
        except:
            pass

"""
@receiver(post_delete, sender=Item)
def post_save_image(sender, instance, *args, **kwargs):
    # Clean Old Image file 
    try:
        instance.image.delete(save=False)
        pass
    except:
        pass
    try:
        instance.image2.delete(save=False)
    except:
        pass
    try:
        instance.image3.delete(save=False)
    except:
        pass
    try:
        instance.thumbnail.delete(save=False)
    except:
        pass
    
pass
"""   
"""       
@receiver(pre_save, sender=Item)
def pre_save_image(sender, instance, *args, **kwargs):
        # instance old image file will delete from os 
        if settings.DROPBOX_MEDIA_STORAGE == True:            
            try:
                dbx = dropbox.Dropbox(
                    app_key = settings.DROPBOX_APP_KEY,
                    app_secret = settings.DROPBOX_APP_SECRET,
                    oauth2_refresh_token = settings.DROPBOX_OAUTH2_REFRESH_TOKEN
                )                
                image_path = "/" + instance.image.name
                try:   # check if image exist in dropbox 
                    dbx_file = dbx.files_get_metadata(image_path)
                    # if exist then delete it
                    #dbx.files_delete(image_path)
                except:
                    pass                 
                    
            except:
                pass        
        
        try:           
            
            old_img = instance.__class__.objects.get(id=instance.id).image.path
                                 
            try:
                new_img = instance.image.path
            except:
                new_img = None
            if new_img != old_img:
                import os
                if os.path.exists(old_img):
                    os.remove(old_img)
                    pass                    
        except:
            pass
        
        try:
            old_img = instance.__class__.objects.get(id=instance.id).image2.path            
            try:
                new_img = instance.image2.path
            except:
                new_img = None
            if new_img != old_img:
                import os
                if os.path.exists(old_img):
                    os.remove(old_img)
                    pass
        except:
            pass
        
        try:
            old_img = instance.__class__.objects.get(id=instance.id).image3.path            
            try:
                new_img = instance.image3.path
            except:
                new_img = None
            if new_img != old_img:
                import os
                if os.path.exists(old_img):
                    os.remove(old_img)
                    pass
        except:
            pass
        
        try:
            old_img = instance.__class__.objects.get(id=instance.id).thumbnail.path            
            try:
                new_img = instance.thumbnail.path
            except:
                new_img = None
            if new_img != old_img:
                import os
                if os.path.exists(old_img):
                    os.remove(old_img)
                    pass
        except:
            pass
"""        
            


        
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,default=1)
    #order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, related_name='items') 
    order = models.ForeignKey('Order', on_delete=models.CASCADE, null=True, blank=True)
    ordered = models.BooleanField(default=False) 
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return  self.order.__str__() + ": " + f"{self.quantity} of {self.item.title}"
    
    def get_total_item_price(self):
        return self.quantity * self.item.price
    
    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price
    
    def get_total_shipping_cost(self):
        print(self.quantity * self.item.shipping_cost)
        return self.quantity * self.item.shipping_cost
    
    def get_amount_saved(self):
        return self.quantity * self.item.price - self.quantity * self.item.discount_price
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price() + self.get_total_shipping_cost()
        return self.get_total_item_price()  + self.get_total_shipping_cost()          

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    order_number = models.CharField(max_length=20,blank=True,default="")    
    #items = models.ManyToManyField(OrderItem, related_name='ordered_items')    

templates/home.html
{% extends "base.html" %}

{% block extra_head %}
<style>
  .img-center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;
  }
</style>

{% endblock extra_head %}

{% block content %}
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">
  
          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'core:home' %}">All
                <span class="sr-only">(current)</span>
              </a>
            </li>

            {% for category in categories %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:category_search' category.id %}">{{category.title}}</a>
              </li>          
            {% endfor%}            

          </ul>
          <!-- Links -->

          <form class="form-inline" name="search" method="GET" action="{% url 'core:home_search' %}">
            
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" name="search" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in items %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                
                {%if item.thumbnail %}
                  {% comment %}
                  <img src="{{ item.thumbnail.url }}" width="50" class="card-img-top">
                  {% endcomment %}                    
                       <img src="{{ item.thumbnail.url }}" class="img-center" >                    
                  {%endif%}
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      {%if item.get_label_display == 'primary' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                      {% endif %}
                      {%if item.get_label_display == 'secondary' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">Lasts in stock!</span>
                      {% endif %}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
                    {% if item.discount_price %}
                    <span class="mr-1">
                      <del>${{ item.price }}</del>
                    </span>
                    <span>${{ item.discount_price }}</span>
                    {% else %}
                    <span>${{ item.price }}</span>
                    {% endif %}
                  </strong>
                </h4>

                {% if item.shipping_cost == 0 %}
                <p class="lead">
                  <span>Free Shipping!!</span>
                </p>              
                {%endif%}

                <h6 class="font-weight-bold red-text">
                  <strong>
                    {% if item.stock < 1 %}                    
                      <span>Out of stock!</span>
                    {% endif %}
                  </strong>
                </h6>



              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">Ecom</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
           <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li>
          {%comment%}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/product">
            Products</a>
          </li>
          {%endcomment%}  
        </ul>

        <!-- Right -->
        
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>              
              
              {%comment%}
              <span class="badge red z-depth-1 mr-1"> {{ request.user }} </span>
              {%endcomment%}
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
         
          {%comment%}
          <li class="nav-item">
            <a class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
           {%endcomment%}
           
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
        
      </div>

    </div>
  </nav>

templates/payment.html
{% extends "base.html" %}

{% block extra_head %}





<style>
    /* Variables */
    * {
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, sans-serif;
      font-size: 16px;
      -webkit-font-smoothing: antialiased;
      
      justify-content: center;
      align-content: center;
      height: 100vh;
      width: 100vw;
    }
    
    form {
      width: 30vw;
      min-width: 500px;
      align-self: center;
      box-shadow: 0px 0px 0px 0.5px rgba(50, 50, 93, 0.1),
        0px 2px 5px 0px rgba(50, 50, 93, 0.1), 0px 1px 1.5px 0px rgba(0, 0, 0, 0.07);
      border-radius: 7px;
      padding: 40px;
    }
    
    .hidden {
      display: none;
    }
    
    #payment-message {
      color: rgb(105, 115, 134);
      font-size: 16px;
      line-height: 20px;
      padding-top: 12px;
      text-align: center;
    }
    
    #payment-element {
      margin-bottom: 50px;
      width:100%
    }
    
    /* Buttons and links */
    button {
      background: #5469d4;
      font-family: Arial, sans-serif;
      color: #ffffff;
      border-radius: 4px;
      border: 0;
      padding: 12px 16px;
      font-size: 16px;
      font-weight: 600;
      cursor: pointer;
      display: block;
      transition: all 0.2s ease;
      box-shadow: 0px 4px 5.5px 0px rgba(0, 0, 0, 0.07);
      width: 100%;
    }
    button:hover {
      filter: contrast(115%);
    }
    button:disabled {
      opacity: 0.5;
      cursor: default;
    }
    
    /* spinner/processing state, errors */
    .spinner,
    .spinner:before,
    .spinner:after {
      border-radius: 50%;
    }
    .spinner {
      color: #ffffff;
      font-size: 22px;
      text-indent: -99999px;
      margin: 0px auto;
      position: relative;
      width: 20px;
      height: 20px;
      box-shadow: inset 0 0 0 2px;
      -webkit-transform: translateZ(0);
      -ms-transform: translateZ(0);
      transform: translateZ(0);
    }
    .spinner:before,
    .spinner:after {
      position: absolute;
      content: "";
    }
    .spinner:before {
      width: 10.4px;
      height: 20.4px;
      background: #5469d4;
      border-radius: 20.4px 0 0 20.4px;
      top: -0.2px;
      left: -0.2px;
      -webkit-transform-origin: 10.4px 10.2px;
      transform-origin: 10.4px 10.2px;
      -webkit-animation: loading 2s infinite ease 1.5s;
      animation: loading 2s infinite ease 1.5s;
    }
    .spinner:after {
      width: 10.4px;
      height: 10.2px;
      background: #5469d4;
      border-radius: 0 10.2px 10.2px 0;
      top: -0.1px;
      left: 10.2px;
      -webkit-transform-origin: 0px 10.2px;
      transform-origin: 0px 10.2px;
      -webkit-animation: loading 2s infinite ease;
      animation: loading 2s infinite ease;
    }
    
    @-webkit-keyframes loading {
      0% {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg);
      }
      100% {
        -webkit-transform: rotate(360deg);
        transform: rotate(360deg);
      }
    }
    @keyframes loading {
      0% {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg);
      }
      100% {
        -webkit-transform: rotate(360deg);
        transform: rotate(360deg);
      }
    }
    
    @media only screen and (max-width: 600px) {
      form {
        width: 80vw;
        min-width: initial;
      }
    }
</style>
<meta name="viewport" content="width=device-width, initial-scale=1" />
{% endblock extra_head %}

    
{% block content %}
  <div class="row">     
    <form id="payment-form">       
            {% csrf_token %}
            {% comment "" %}
              <div id="link-authentication-element" >
              <!--Stripe.js injects the Link Authentication Element-->
              </div>
            {% endcomment %}
            <div id="payment-element">
            <!--Stripe.js injects the Payment Element-->
            </div>
            <button id="submit">
            <div class="spinner hidden" id="spinner"></div>
            <span id="button-text">Pay now</span>
            </button>
            <div id="payment-message" class="hidden"></div>                 
    </form>

    <div class="col-md-4 mb-4">
      {% include "order_snippet.html" %}
    </div>
  
  </div>
  
{% endblock content %}



{% block extra_scripts %}
     


    <script src="https://js.stripe.com/v3/"></script>

    

    <script>  // Create a Stripe client.

       

        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        //const stripe = Stripe('{{STRIPE_PUBLIC_KEY}}');
        //const stripe = Stripe('{{STRIPE_SECRET_KEY}}');
        const stripe = Stripe("pk_test_51MOko7Aov1Y18T3vkG2bNiaDuIRoovmjMdAH6i1OuC4zeckKXDH5dOM3vNh2iEq2fmG9JWhHrHps3S4OAI7lMcLA00oBGVYhMK");

        // The items the customer wants to buy
        const items = [{ id: "xl-tshirt" }];

        let elements;

        initialize();
        checkStatus();

        document
        .querySelector("#payment-form")
        .addEventListener("submit", handleSubmit);

        var emailAddress = '';
        // Fetches a payment intent and captures the client secret
        async function initialize() {
        
            const response = await fetch("{% url 'core:create-payment-intent' %}", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    'X-CSRFToken': csrftoken 
                },
                //body: JSON.stringify({ items }),
            });            
            
            const { clientSecret } = await response.json();
            
            const appearance = {
                theme: 'stripe',
            };
            
            //console.log(response)            
            elements = stripe.elements({ appearance, clientSecret });            
            
           // const linkAuthenticationElement = elements.create("linkAuthentication");
           // linkAuthenticationElement.mount("#link-authentication-element");           

           // linkAuthenticationElement.on('change', (event) => {
           //     emailAddress = event.value.email;
           //  });

            const paymentElementOptions = {
                layout: "tabs",
            };

            const paymentElement = elements.create("payment", paymentElementOptions);
            
            paymentElement.mount("#payment-element");
        }

        

        async function handleSubmit(e) {
                        
            e.preventDefault();
            setLoading(true);

            var s_url = "http://"+ window.location.host + "{% url 'core:create-payment-success' %}";
            //console.log(s_url)

            const { error } = await stripe.confirmPayment({
                elements,
                confirmParams: {
                // Make sure to change this to your payment completion page
                return_url: s_url,
                //return_url: "http://127.0.0.1:9000/create-payment-success/",
                receipt_email: emailAddress,
                },
            });            
            
            // This point will only be reached if there is an immediate error when
            // confirming the payment. Otherwise, your customer will be redirected to
            // your `return_url`. For some payment methods like iDEAL, your customer will
            // be redirected to an intermediate site first to authorize the payment, then
            // redirected to the `return_url`.
            if (error.type === "card_error" || error.type === "validation_error") {
                showMessage(error.message);
            } else {
                // console.log(error.message)
                showMessage("An unexpected error occurred.");
            }

            setLoading(false);
        }

        // Fetches the payment intent status after payment submission
        async function checkStatus() {
            const clientSecret = new URLSearchParams(window.location.search).get(
                "payment_intent_client_secret"
            );

            if (!clientSecret) {
                return;
            }

            const { paymentIntent } = await stripe.retrievePaymentIntent(clientSecret);

            switch (paymentIntent.status) {
                case "succeeded":
                showMessage("Payment succeeded!");
                break;
                case "processing":
                showMessage("Your payment is processing.");
                break;
                case "requires_payment_method":
                showMessage("Your payment was not successful, please try again.");
                break;
                default:
                showMessage("Something went wrong.");
                break;
            }
        }

        // ------- UI helpers -------

        function showMessage(messageText) {
        const messageContainer = document.querySelector("#payment-message");

        messageContainer.classList.remove("hidden");
        messageContainer.textContent = messageText;

        setTimeout(function () {
            messageContainer.classList.add("hidden");
            messageText.textContent = "";
        }, 4000);
        }

        // Show a spinner on payment submission
        function setLoading(isLoading) {
        if (isLoading) {
            // Disable the button and show a spinner
            document.querySelector("#submit").disabled = true;
            document.querySelector("#spinner").classList.remove("hidden");
            document.querySelector("#button-text").classList.add("hidden");
        } else {
            document.querySelector("#submit").disabled = false;
            document.querySelector("#spinner").classList.add("hidden");
            document.querySelector("#button-text").classList.remove("hidden");
        }
        }

        function demo(a) {
            if(typeof a === 'object' && a != null && Object.keys(a).length !== 0){
                return false;
            } else {
                return true;
            }
        }
            

    </script>

    {% endblock extra_scripts %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>